resolver: lts-20.26
install-ghc: true

extra-deps:
  - url: https://github.com/codewars/hspec-formatters-codewars/archive/v0.3.0.tar.gz
  - url: https://github.com/codewars/hspec-codewars/archive/v0.1.0.tar.gz
